In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ocorrencia.csv", sep=";", parse_dates=['ocorrencia_dia'], dayfirst=True)
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,45331,ACIDENTE,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,27/11/2013,0,1,NÃO

In [3]:
df.loc[1,'ocorrencia_cidade']

'GUARULHOS'

In [4]:
df.loc[3]

codigo_ocorrencia                               45401
codigo_ocorrencia1                              45401
codigo_ocorrencia2                              45401
codigo_ocorrencia3                              45401
codigo_ocorrencia4                              45401
ocorrencia_classificacao                     ACIDENTE
ocorrencia_latitude                               ***
ocorrencia_longitude                              ***
ocorrencia_cidade                       SÃO SEBASTIÃO
ocorrencia_uf                                      SP
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             ****
ocorrencia_dia                    2012-01-06 00:00:00
ocorrencia_hora                              17:00:00
investigacao_aeronave_liberada                    ***
investigacao_status                               NaN
divulgacao_relatorio_numero                       NaN
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 3, dtype: object

In [5]:
df.loc[1:3]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
1,45331,45331,45331,45331,45331,ACIDENTE,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO

In [7]:
df.loc[[10,40]]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
10,45332,45332,45332,45332,45332,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-09,13:30:00,SIM,FINALIZADA,A-072/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
40,45415,45415,45415,45415,45415,ACIDENTE,***,***,RIO DE JANEIRO,RJ,...,2012-01-30,13:55:00,SIM,FINALIZADA,A-077/CENIPA/2013,SIM,21/10/2013,0,1,NÃO

In [8]:
df.loc[:,'ocorrencia_cidade']

0        PORTO ALEGRE
1           GUARULHOS
2              VIAMÃO
3       SÃO SEBASTIÃO
4            SÃO SEPÉ
            ...
5162            JATAÍ
5163          MARACAÍ
5164    NOVO HAMBURGO
5165         CURITIBA
5166        PETROLINA
Name: ocorrencia_cidade, Length: 5167, dtype: object

In [10]:
df.codigo_ocorrencia.is_unique

True

In [13]:
df.set_index('codigo_ocorrencia', inplace=True)

In [14]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,BRASIL,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
45331,45331,45331,45331,45331,ACIDENTE,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,BRASIL,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,3,1,NÃO
45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,BRASIL,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,BRASIL,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,27/11/2013,0,1,NÃO

In [16]:
df.loc[45333]

codigo_ocorrencia1                              45333
codigo_ocorrencia2                              45333
codigo_ocorrencia3                              45333
codigo_ocorrencia4                              45333
ocorrencia_classificacao                     ACIDENTE
ocorrencia_latitude                               ***
ocorrencia_longitude                              ***
ocorrencia_cidade                              VIAMÃO
ocorrencia_uf                                      RS
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             ****
ocorrencia_dia                    2012-01-06 00:00:00
ocorrencia_hora                              13:00:00
investigacao_aeronave_liberada                    NaN
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero         A-070/CENIPA/2013
divulgacao_relatorio_publicado                    SIM
divulgacao_dia_publicacao                  27/11/2013
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 45333, dtype: object

In [17]:
df.reset_index(drop=True, inplace=True)

In [18]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,BRASIL,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,ACIDENTE,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,BRASIL,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,3,1,NÃO
2,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,BRASIL,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,0,1,NÃO
3,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,BRASIL,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,27/11/2013,0,1,NÃO

In [21]:
df.loc[0,'ocorrencia_pais'] = ''

In [22]:
df.head(1)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [23]:
df.loc[:, 'total_recomendacoes'] = 10

In [24]:
df

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,10,1,NÃO
1,45331,45331,45331,45331,ACIDENTE,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,BRASIL,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,10,1,NÃO
2,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,BRASIL,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,10,1,NÃO
3,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO
4,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,BRASIL,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,27/11/2013,10,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5162,80458,80458,80458,80458,ACIDENTE,-17.999.194,-51.642.861,JATAÍ,GO,BRASIL,...,2021-12-30,20:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,NÃO
5163,80452,80452,80452,80452,ACIDENTE,-22.585.556,-50.753.889,MARACAÍ,SP,BRASIL,...,2021-12-31,09:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,NÃO
5164,80457,80457,80457,80457,INCIDENTE GRAVE,-29.695.833,-51.081.667,NOVO HAMBURGO,RS,BRASIL,...,2021-12-31,11:59:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO
5165,80460,80460,80460,80460,INCIDENTE,-25.403.333,-49.233.611,CURITIBA,PR,BRASIL,...,2021-12-31,15:12:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO
5166,80467,80467,80467,80467,INCIDENTE,-93.675,-4.056.361.111.111,PETROLINA,PE,BRASIL,...,2021-12-31,20:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO

In [25]:
df['ocorrencia_uf_bkp'] = df.ocorrencia_uf

In [26]:
df

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,,...,20:27:00,***,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RS
1,45331,45331,45331,45331,ACIDENTE,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,BRASIL,...,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,10,1,NÃO,SP
2,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,BRASIL,...,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,10,1,NÃO,RS
3,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,17:00:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
4,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,BRASIL,...,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,27/11/2013,10,1,NÃO,RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5162,80458,80458,80458,80458,ACIDENTE,-17.999.194,-51.642.861,JATAÍ,GO,BRASIL,...,20:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,NÃO,GO
5163,80452,80452,80452,80452,ACIDENTE,-22.585.556,-50.753.889,MARACAÍ,SP,BRASIL,...,09:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,NÃO,SP
5164,80457,80457,80457,80457,INCIDENTE GRAVE,-29.695.833,-51.081.667,NOVO HAMBURGO,RS,BRASIL,...,11:59:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RS
5165,80460,80460,80460,80460,INCIDENTE,-25.403.333,-49.233.611,CURITIBA,PR,BRASIL,...,15:12:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,PR
5166,80467,80467,80467,80467,INCIDENTE,-93.675,-4.056.361.111.111,PETROLINA,PE,BRASIL,...,20:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,PE

In [27]:
df.loc[df.ocorrencia_uf == 'SP', ['ocorrencia_classificacao']] = 'Grave'

In [28]:
df

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,,...,20:27:00,***,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RS
1,45331,45331,45331,45331,Grave,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,BRASIL,...,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,10,1,NÃO,SP
2,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,BRASIL,...,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,27/11/2013,10,1,NÃO,RS
3,45401,45401,45401,45401,Grave,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,17:00:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
4,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,BRASIL,...,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,27/11/2013,10,1,NÃO,RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5162,80458,80458,80458,80458,ACIDENTE,-17.999.194,-51.642.861,JATAÍ,GO,BRASIL,...,20:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,NÃO,GO
5163,80452,80452,80452,80452,Grave,-22.585.556,-50.753.889,MARACAÍ,SP,BRASIL,...,09:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,NÃO,SP
5164,80457,80457,80457,80457,INCIDENTE GRAVE,-29.695.833,-51.081.667,NOVO HAMBURGO,RS,BRASIL,...,11:59:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RS
5165,80460,80460,80460,80460,INCIDENTE,-25.403.333,-49.233.611,CURITIBA,PR,BRASIL,...,15:12:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,PR
5166,80467,80467,80467,80467,INCIDENTE,-93.675,-4.056.361.111.111,PETROLINA,PE,BRASIL,...,20:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,PE

In [30]:
df.loc[df.ocorrencia_uf == 'SP']

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
1,45331,45331,45331,45331,Grave,-234.355.555.556,-464.730.555.556,GUARULHOS,SP,BRASIL,...,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,01/09/2016,10,1,NÃO,SP
3,45401,45401,45401,45401,Grave,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,17:00:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
5,52243,52243,52243,52243,Grave,NaN,NaN,UBATUBA,SP,BRASIL,...,14:30:00,***,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP
6,50713,50713,50713,50713,Grave,***,***,CAMPINAS,SP,BRASIL,...,18:15:00,SIM,FINALIZADA,IG-184/CENIPA/2013,SIM,08/01/2014,10,1,NÃO,SP
13,45408,45408,45408,45408,Grave,-245.888.888.889,-482.113.888.889,ELDORADO,SP,BRASIL,...,13:45:00,SIM,FINALIZADA,A-509/CENIPA/2021,SIM,08/07/2021,10,1,NÃO,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5148,80441,80441,80441,80441,Grave,-230.052,-466.336,BRAGANÇA PAULISTA,SP,BRASIL,...,18:15:00,NÃO,ATIVA,A DEFINIR,NÃO,NaN,10,1,SIM,SP
5157,80453,80453,80453,80453,Grave,-2.300.694.444.444,-4.713.444.444.444,CAMPINAS,SP,BRASIL,...,09:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP
5158,80454,80454,80454,80454,Grave,-21.144.167,-50.426.389,ARAÇATUBA,SP,BRASIL,...,21:35:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,SIM,SP
5161,80456,80456,80456,80456,Grave,-23.626.111,-46.656.389,SÃO PAULO,SP,BRASIL,...,13:15:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,SIM,SP
5163,80452,80452,80452,80452,Grave,-22.585.556,-50.753.889,MARACAÍ,SP,BRASIL,...,09:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,NÃO,SP